version: "3.8"
services:
  app:
    container_name: race-events
    image: race-events
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001